routes/web.php
<?php

use App\Http\Controllers\AdminController;
use App\Http\Controllers\CinemaController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [CinemaController::class, 'index'])->name('index');
Route::get('/genres/{name}', [CinemaController::class, 'sorting'])->name('sorting');

Route::get('/search', function () {
    return view('guest.search');
})->name('search');

Route::post('/search/', [CinemaController::class, 'show'])->name('search-form');


Route::middleware('auth')->group(function () {

    Route::resource('admin/films', 'App\Http\Controllers\AdminController',
        ['parameters' =>[
    'films' => 'id']]
    );

});

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
//Auth::logout();

Auth::routes([
    'register' => false,
    'verify' => false,
    'reset' => false
]);

//

resources/views/admin/add.blade.php
@extends('admin.app.schema')
<?php
$genre_model = new App\Models\genre_list();
$genres = $genre_model->genres();
?>
@section('title','Add')

@section('content')
    <form action="{{route('films.store')}}" method="post">
        @csrf
        <p>
            <label for="genre_id">Жанр</label>
            <select name="genre_id" id="genre_id">
                @foreach($genres as $genre)
                    <option value='{{ $genre->genre_id }}'>{{ $genre->genre_name }}</option>
                @endforeach
            </select>
        </p>
        <p>
            <label for="name">Назва фільму:</label>
            <input name="name" id="name" type="text">
        </p>
        <p>
            <label for="country">Країна виробництва:</label>
            <input name="country" id="country" type="text">
        </p>
        <p>
            <label for="year">Рік випуску:</label>
            <input name="year" id="year" type="text">
        </p>
        <p>
            <button type="submit">Додати</button>
            <a href="{{route('films.index')}}">Назад</a>
        </p>
    </form>
@endsection

resources/views/admin/edit.blade.php
@extends('admin.app.schema')
@foreach($result as $row)
    <?php
    $genre_model = new App\Models\genre_list();
    $genres = $genre_model->genres();
    ?>
    @section('title','Edit')

@section('content')
    <form action="{{route('films.update',['id' => $row->id])}}"method="post">
        <input name="_method" type="hidden" value="PUT">
        @csrf
        <p>
            <label for="genre_id">Жанр</label>
            <select name="genre_id" id="genre_id">
                @foreach($genres as $genre)
                    <option value='{{ $genre->genre_id }}'>{{ $genre->genre_name }}</option>
                @endforeach
            </select>
        </p>
        <p>
            <label for="name">Назва фільму:</label>
            <input name="name" id="name" type="text" value="{{$row->name}}">
        </p>
        <p>
            <label for="country">Країна виробництва:</label>
            <input name="country" id="country" type="text"  value="{{$row->country}}">
        </p>
        <p>
            <label for="year">Рік випуску:</label>
            <input name="year" id="year" type="text"  value="{{$row->year}}">
        </p>
        <p>
            <button type="submit">Редагувати</button>
            <a href="{{route('films.index')}}">Назад</a>
        </p>
    </form>
@endsection
@endforeach

resources/views/admin/index.blade.php
@extends('admin.app.schema')

@section('title','Admin main')

@section('content')
    <p>
        <a href="{{route('films.create')}}">Додати фільм</a>
        <a href="{{ route('logout') }}"
           onclick="event.preventDefault();document.getElementById('logout-form').submit();">
            {{ __('Вийти') }}
        </a>
    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
        @csrf
    </form>
    </p>
    @if(isset($result))
        <table>
            <thead>
            <tr>
                <th>Назва фільму</th>
                <th>Action</th>
            </tr>
            </thead>
            <tbody>
            @foreach($result as $row)
                <tr>
                    <td>{{$row->name}}</td>
                    <td style="width: 200px">
                        <a href="{{route('films.show' , ['id' => $row->id])}}">Інфо</a>
                        |
                        <a href="{{route('films.edit', ['id' => $row->id])}}">Змінити</a>
                        |
                        <form action="{{ route('films.destroy' , ['id'=> $row->id])}}" method="POST">
                            <input name="_method" type="hidden" value="DELETE">
                            {{ csrf_field() }}
                            <button type="submit">Видалити</button>
                        </form>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    @endif
@endsection

resources/views/admin/info.blade.php
@foreach($result as $row)
    @extends('admin.app.schema')

    @section('title',$row->name)
@section('content')
    @if(isset($result))
        <table>
            <thead>
            <tr>
                <th>Назва фільму</th>
                <th>Жанр</th>
                <th>Країна виробництва</th>
                <th>Рік виходу</th>
            </tr>
            </thead>
            <tbody>
            @foreach($result as $row)
                <tr>
                    <td>{{$row->name}}</td>
                    <td>{{$row->genre_name}}</td>
                    <td>{{$row->country}}</td>
                    <td>{{$row->year}}</td>
                </tr>
            @endforeach
            </tbody>
        </table>
        <p>
            <a href="{{route('films.edit',['id' => $row->id])}}">Редагувати</a>
        <form action="{{ route('films.destroy' , ['id'=> $row->id])}}" method="POST">
            <input name="_method" type="hidden" value="DELETE">
            {{ csrf_field() }}
            <button type="submit">Видалити</button>
        </form>
        </p>
    @endif
@endsection
@endforeach